name-template: "$REPOSITORY_NAME $NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

exclude-labels:
  - "ignore-for-release"
  - "skip-changelog"
  - "meta"
  - "chore"

exclude-contributors:
  - "octocat"
  - "dependabot[bot]"
  - "renovate[bot]"

categories:
  - title: "🛠 Breaking Changes"
    labels:
      - "Semver-Major"
      - "breaking-change"
  - title: "🎉 Exciting New Features"
    labels:
      - "Semver-Minor"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "Semver-Patch"
      - "bug"
      - "fix"
  - title: "📄 Documentation"
    labels:
      - "docs"
      - "documentation"
  - title: "🧹 Maintenance & Refactoring"
    labels:
      - "refactor"
      - "code-cleanup"
      - "maintenance"
  - title: "🧪 Tests"
    labels:
      - "test"
      - "testing"
  - title: "📦 Dependency Updates"
    labels:
      - "dependencies"
      - "build"
      - "ci"
  - title: "📂 Uncategorized"
    labels:
      - "*"

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

template: |
  ### What's Changed

  $CHANGES

  ---

  🛠 This release was automatically generated using [Release Drafter](https://github.com/release-drafter/release-drafter).
