name: Detect changed files
description: Detect whether files matching patterns changed
inputs:
  files:
    description: Files or patterns to check for changes
    required: true
outputs:
  model_changed:
    description: Indicates if any models changed 
    value: ${{ steps.changed.outputs.any_changed  }}

runs:
  using: "composite"
  steps:
    - id: changed
      uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 
      with:
        files: ${{ inputs.files }}
