name: GitHub Tag, Docker publish build, SSH Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
!      - # The name of your test workflow (example: Run Pytest with Coverage, Check the Alembic Migration and run the Sonar Analysis)
    types:
      - completed
  pull_request:
    types:
      - labeled

run-name: Deploy branch ${{ github.event.workflow_run.head_branch || 'main' }} by @${{ github.actor }}

jobs:
  tag:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/generate-github-tag.yml@main

  # This job will only run if ran from the main branch
  create-release:
    needs: tag
    uses: repowerednl/.github/.github/workflows/release-notes-generator.yml@main
    with:
      tag: ${{ needs.tag.outputs.tag }}

  # Only for the front-end; delete this job if you don't have a 'package.json'
  # If you do, add bump to the 'needs' section -> needs: [tag, bump]
  bump:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/bump-package-json.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      # node_version: # Optional, defaults to "20"
      # working_directory: # Optional, defaults to '.'.

  # Repeat steps below if there are multiple Dockerfiles and/or docker-compose files
  github-environment:
    permissions:
      pull-requests: read
    uses: repowerednl/.github/.github/workflows/determine-environment.yml@main

  docker:
    uses: repowerednl/.github/.github/workflows/docker-build-and-push.yml@main
    needs: [tag, github-environment]
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      environment: ${{ needs.github-environment.outputs.environment }}
      # dockerfile_name: # Optional, defaults to 'Dockerfile'
      # build_argument_one: # Optional, no default; from GitHub Variables
      # build_argument_two: # Optional, no default; from GitHub Variables
      # build_argument_three: # Optional, no default; from GitHub Variables
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  deploy:
    needs: [ docker, tag ]
    uses: repowerednl/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: ${{ needs.docker.outputs.environment }}
      tag: ${{ needs.tag.outputs.tag }}
      # server_username: Optional, defaults to 'root'
      # docker-compose_remote_dir: Optional, defaults to '/root'
      # docker-compose_file_path: Optional, defaults to 'docker-compose.yml'
    secrets: inherit
