name: GitHub Tag, Docker publish build, SSH Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_run:
    workflows:
!      - # The name of your test workflow (example: Run Pytest with Coverage, Check the Alembic Migration and run the Sonar Analysis)
    types:
      - completed

jobs:
  tag:
    if: >
      ((github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') ||
      (github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success') && contains(github.event.workflow_run.head_commit.message, '[deploy]')))
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/generate-github-tag.yml@main


  # Only for the front-end; delete this job if you don't have a 'package.json'
  bump:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/bump-package-json.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      # node_version: # Optional, defaults to "20"
      # working_directory: # Optional, defaults to '.'.

  # Repeat steps below if there are multiple Dockerfiles and/or docker-compose files

  docker:
    uses: repowerednl/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      # dockerfile_name: # Optional, defaults to 'Dockerfile'
      # build_argument_one: # Optional, no default; from GitHub Variables
      # build_argument_two: # Optional, no default; from GitHub Variables
      # build_argument_three: # Optional, no default; from GitHub Variables
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  environment:
    if: >
      ((github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') ||
      (github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success') && contains(github.event.workflow_run.head_commit.message, '[deploy]')))
    uses: repowerednl/.github/.github/workflows/determine-environment.yml@main

  deploy:
    needs: [ environment, docker, tag ]
    uses: repowerednl/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: ${{ needs.environment.outputs.environment }}
      tag: ${{ needs.tag.outputs.tag }}
      # extra_reroute_domain: Optional, no default
      # server_username: Optional, defaults to 'root'
      # docker-compose_remote_dir: Optional, defaults to '/root'
      # docker-compose_file_path: Optional, defaults to 'docker-compose.yml'
    secrets: inherit
