name: GitHub Tag, Docker publish build, Kubernetes Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
!      - # The actual name of your TEST workflow (example: Run Yarn commands (install, check-updates, lint, prettier, test with coverage and/or build with publish) and run the Sonar Analysis)
    types:
      - completed

run-name: Deploy branch ${{ github.event.workflow_run.head_branch }} by @${{ github.actor }}

jobs:
  tag:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/generate-github-tag.yml@main

  # Only for the front-end; delete this job if you don't have a 'package.json'
  # If you do, add bump to the 'needs' section for docker -> needs: [tag, bump]
  bump:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/bump-package-json.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      # node_version: # Optional, defaults to "20"
      # working_directory: # Optional, defaults to '.'.

  # Repeat steps docker + deploy-verify if there are multiple Dockerfiles

  github-environment:
    permissions:
      pull-requests: read
    uses: repowerednl/.github/.github/workflows/determine-environment.yml@main

  docker:
    uses: repowerednl/.github/.github/workflows/docker-build-and-push.yml@main
    needs: [ tag, github-environment ]
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      environment: ${{ needs.github-environment.outputs.environment }}
      # dockerfile_name: # Optional, defaults to 'Dockerfile'
      # build_argument_one: # Optional, no default; from GitHub Variables
      # build_argument_two: # Optional, no default; from GitHub Variables
      # build_argument_three: # Optional, no default; from GitHub Variables
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  # TODO(REP-2945): Move this step to the repository infra
  # Should only be active for repower-django (add job to 'needs' in deploy-verify)
  #  run-migrations:
  #    uses: repowerednl/.github/.github/workflows/run-kube-migration.yml@main
  #    needs: tag
  #    with:
  #      tag: ${{ needs.tag.outputs.tag }}
  #    secrets: inherit

  deploy-verify:
    uses: repowerednl/.github/.github/workflows/deploy-verify-kubernetes.yml@main
    needs: [ docker ]
    with:
      # If there are multiple deployments for a single docker image, the container names can be specified here
      # Example:
      # Dockerfile 'hello-world' is responsible for the following deployments: foo, bar
      # the corresponding container_names are: "['foo', 'bar']"
      container_names: # A JSON list string i.e. "['my name']"
      docker_image_tag: ${{ needs.docker.outputs.image_tag }}
      environment: ${{ needs.docker.outputs.environment }}
      # with_infisical_configuration: # Optional, defaults to false
    secrets:
      digital_ocean_access_token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      # infisical_client_id: ${{ secrets.INFISICAL_CLIENT_ID }}
      # infisical_client_client_secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
      # infisical_client_project_id: ${{ secrets.INFISICAL_PROJECT_ID }}
