name: Pytest, Sphinx Docs and Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pytest-simple-with-coverage:
    # Make sure that the uv/poetry versions are aligned with the selected workflow
    uses: repowerednl/.github/.github/workflows/python-uv-test-coverage-simple.yml@main
    permissions:
      pull-requests: write
      contents: write
      actions: read
    strategy:
      matrix:
        # Make sure that the configured python versions are available here.
        # These versions are cached on the runner; otherwise setting up python is too slow for the CI
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/toolsets/toolset-2004.json#L4
        # python_version: [ "3.11.2" ]
        # poetry_version: [ "1.8.4" ]
        uv_version: [ "0.9.4" ]
    with:
      # python_version: ${{ matrix.python_version }}
      # poetry_version: ${{ matrix.poetry_version }}
      uv_version: ${{ matrix.uv_version }}
      # The poetry cached installation is in '/home/runner/.local/' and the './.venv' is for the poetry packages
      # when configuring a working directory, make sure the cached paths are also up-to-date
      # file_paths_to_cache: |
      #   .venv
      #   /home/runner/.local/
      # working_directory: # Optional, defaults to '.'
    secrets:
      # private_pypi_url: ${{ secrets.PRIVATE_PYPI_URL }} # Is required for poetry (also below)
      private_pypi_user: ${{ secrets.PRIVATE_PYPI_USER }}
      private_pypi_password: ${{ secrets.PRIVATE_PYPI_PASSWORD }}

  tag:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/generate-github-tag.yml@main

  bump-package-json:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/bump-package-json.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      app-id: ${{ vars.APP_ID }}
    secrets:
      private-key: ${{ secrets.APP_PRIVATE_KEY }}

  # This job will only run if ran from the main branch
  create-release:
    needs: tag
    uses: repowerednl/.github/.github/workflows/release-notes-generator.yml@main
    with:
      tag: ${{ needs.tag.outputs.tag }}

  deploy-uv-sphinx-documentation:
    needs: [create-release, bump-package-json]
    # Make sure that the uv/poetry versions are aligned with the selected workflow
    uses: repowerednl/.github/.github/workflows/deploy-uv-sphinx-documentation.yml@DATA-323-Create-default-Sphinx-docs-folder-and-store-it-somewhere
    # uses: repowerednl/.github/.github/workflows/deploy-sphinx-documentation.yml@main
    with:
      # python_version: "3.11.2"
      # poetry_version: "1.8.4"
      uv_version: "0.9.4"
      # The poetry cached installation is in '/home/runner/.local/' and the './.venv' is for the poetry packages
      # when configuring a working directory, make sure the cached paths are also up-to-date
      # file_paths_to_cache: |
      #   .venv
      #   /home/runner/.local/
      docs_target: /home/repowered/docs/<package-name> # ------------- Configure manually! If left default or blank, docs are built but won't be deployed! -------------
    secrets:
      private_pypi_user: ${{ secrets.PRIVATE_PYPI_USER }}
      private_pypi_password: ${{ secrets.PRIVATE_PYPI_PASSWORD }}
      docs_ssh_private_key: ${{ secrets.DOCS_SSH_PRIVATE_KEY }}

  release:
    needs: [tag, create-release]
    # Make sure that the uv/poetry versions are aligned with the selected workflow
    uses: repowerednl/.github/.github/workflows/release-uv-pypi-package.yml@main
    # uses: repowerednl/.github/.github/workflows/release-pypi-package.yml@main
    with:
      tag: ${{ needs.tag.outputs.tag }}
      # python_version: "3.11.2"
      uv_version: "0.9.4"
      # poetry_version: "1.8.4"
      # poetry_no_root: false
      # The poetry cached installation is in '/home/runner/.local/' and the './.venv' is for the poetry packages
      # when configuring a working directory, make sure the cached paths are also up-to-date
      # file_paths_to_cache: |
      #   .venv
      #   /home/runner/.local/
    secrets:
      # private_pypi_url: ${{ secrets.PRIVATE_PYPI_URL }}
      private_pypi_user: ${{ secrets.PRIVATE_PYPI_USER }}
      private_pypi_password: ${{ secrets.PRIVATE_PYPI_PASSWORD }}
      publish_pypi_url: ${{ secrets.PRIVATE_PYPI_PUBLISH_URL}}
