name: Run Yarn commands (install, check-updates, lint, prettier, test with coverage and/or build with publish) and run the Sonar Analysis

on:
  push:
    branches:
      - dev
      - hotfix**
  pull_request:
    branches-ignore:
      - main

jobs:
  yarn-check-lint-prettier-test-publish:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/yarn-check-lint-prettier-test-publish.yml@main
    with:
      should_publish: false # Replace with ${{ endsWith( GITHUB.REF, 'main') }} to enable publishing
      should_test: true
      # prettier_check_content: # Optional, defaults to "{json-server,src}/**/*.{js,vue,json,html,css,md}"
      # node_version: # Optional, defaults to "20"
      # working_directory: # Optional, defaults to '.'
    secrets:
      npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}


  sonar-cloud:
    needs: yarn-check-lint-prettier-test-publish
    uses: repowerednl/.github/.github/workflows/quality-control-sonar.yml@main
    # with:
      # coverage_report_name: # Optional, defaults to 'coverage.xml'
    secrets: inherit


