name: Run Yarn commands (install, check-updates, lint, prettier, test with coverage and/or build with publish) and run the Sonar Analysis

on:
  push:
    branches:
      - dev
      - hotfix**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches-ignore:
      - main

jobs:
  draft-pr-check:
        uses: repowerednl/.github/.github/workflows/check-draft.yml@main
        with:
          is-draft: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft }}
  yarn-check-lint-prettier-test-publish:
    needs: draft-pr-check
    permissions:
      contents: write
      packages: read
    uses: repowerednl/.github/.github/workflows/yarn-check-lint-prettier-test-publish.yml@main
    with:
      should_publish: false # Replace with ${{ endsWith( GITHUB.REF, 'main') }} to enable publishing
      should_test: true
      # prettier_check_content: # Optional, defaults to "{json-server,src}/**/*.{js,vue,json,html,css,md}"
      # node_version: # Optional, defaults to "20"
      # working_directory: # Optional, defaults to '.'
    secrets:
      packages_auth_token: ${{ secrets.GITHUB_TOKEN }}


  sonar-cloud:
    needs: yarn-check-lint-prettier-test-publish
    uses: repowerednl/.github/.github/workflows/quality-control-sonar.yml@main
    # with:
      # coverage_report_name: # Optional, defaults to 'coverage.xml'
    secrets: inherit


