name: "[Deprecated] Update package.json with a given tag (use update-version-files instead)"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "The Semantic Versioning GitHub tag used for version control"
      app-id:
        required: true
        type: string
      # Optional
      version_files:
        required: false
        type: string
        default: "package.json"
        description: "Comma separated files to bump"
      node_version:
        required: false
        type: string
        default: "20"
        description: "[Deprecated] No longer used, the bump no longer runs npm"
    secrets:
      private-key:
        required: true

jobs:
  update-package-json:
    permissions:
      contents: write
    uses: repowerednl/.github/.github/workflows/update-version-files.yml@IN-598-extend-bump-other-versioning-files
    with:
      tag: ${{ inputs.tag }}
      app-id: ${{ inputs.app-id }}
      version_files: ${{ inputs.version_files }}
    secrets:
      private-key: ${{ secrets.private-key }}
