name: Update package.json with a given tag

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "The Semantic Versioning GitHub tag used for version control"

jobs:
  update-package-json:
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v11.0.7
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: "#major"
          minor-wording: "#minor"
          patch-wording: "#patch"
          skip-tag:  "true" # Already done in another (reusable) workflow
          target-branch: "dev"
          commit-message: "Auto bump version of package.json to {{version}} [skip ci]"

      - name: Equality of Version Bump and Git Tag
        run: |
          if [ "${{ steps.version-bump.outputs.newTag }}" != "${{ inputs.tag }}" ]; then
            echo ":x: Version bump tag and GitHub tag do not match!" >> $GITHUB_STEP_SUMMARY
            echo "Version bump tag: ${{ steps.version-bump.outputs.newTag }}" >> $GITHUB_STEP_SUMMARY
            echo "GitHub pushed tag: ${{ inputs.tag }}" >> $GITHUB_STEP_SUMMARY
            echo "Please contact the DevOps creator for this error " >> $GITHUB_STEP_SUMMARY
          else
            echo ":white_check_mark: Version bump tag and GitHub tag match: ${{ inputs.tag }}." >> $GITHUB_STEP_SUMMARY
          fi

