name: Update package.json with a given tag

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "The Semantic Versioning GitHub tag used for version control"
      # Optional
      node_version:
        required: false
        type: string
        default: "20"

jobs:
  update-package-json:
    if: ${{ github.ref == 'refs/heads/main' }}
    continue-on-error: true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Bump Version
        run: |
          VERSION="${{ inputs.tag }}"
          VERSION="${VERSION#v}"  # Remove leading 'v' if present
          npm version "$VERSION" --no-git-tag-version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH="bump-version-$VERSION-$(date +%s)"
          git checkout -b "$BRANCH"
          git add package.json package-lock.json
          git commit -m "Automated version bump to $VERSION [skip-ci]"
          git push origin HEAD

      - name: Create PR for version bump
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Release version bump: ${{ inputs.tag }}"
          body: "Automated version bump [skip-ci]"
          base: dev
