name: Determine GitHub environment
# Since reusable workflows cannot handle environments they need to be retrieved separately:
# https://docs.github.com/en/enterprise-cloud@latest/actions/sharing-automations/reusing-workflows#limitations

on:
  workflow_call:
    outputs:
      environment:
        description: "The GitHub's environment"
        value: ${{ jobs.determine-environment.outputs.env_name }}

jobs:
  determine-environment:
    name: Determine the GitHub environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.retrieve-environment.outputs.env_name }}
    steps:
      - name: Retrieve environment
        id: retrieve-environment
        #TODO(REP-2853): temporarily also qa environment until the rollback workflow is in place
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.pull_request.base.ref }}" = "main" ]; then
            echo "env_name=qa" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi