name: Docker build and push

on:
  workflow_call:
    inputs:
      # Required
      tag:
        description: The Semantic Versioning tag (generated in a different workflow)
        type: string
        required: true
      docker_hub_username:
        required: true
        type: string
      environment:
        description: The environment the docker image is build for
        type: string
        required: true
      # Optional
      dockerfile_name:
        type: string
        required: false
        default: Dockerfile
      build_argument_one:
        required: false
        type: string
        description: A build argument for the Dockerfile
      build_argument_two:
        required: false
        type: string
        description: A build argument for the Dockerfile
      build_argument_three:
        required: false
        type: string
        description: A build argument for the Dockerfile
    outputs:
      image_tag:
        description: "The docker image tag following the structure: <docker hub username>/<repository>[-<name>]:<semver version>"
        value: ${{ jobs.generate-image-tag-set-environment.outputs.image_tag }}
      environment:
        description: propagate the environment used in the docker build to (an)other job(s)
        value: ${{ jobs.generate-image-tag-set-environment.outputs.environment }}
    secrets:
      docker_hub_access_token:
        required: true
      docker_secret_1:
      docker_secret_2:
      docker_secret_3:
      docker_secret_4:
      docker_secret_5:
      docker_secret_6:

jobs:
  generate-image-tag-set-environment:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.docker-image-tag-env.outputs.image_tag }}
      environment: ${{ steps.docker-image-tag-env.outputs.environment }}
    steps:
      # Sets the docker image tag according to the file system structure of Dockerhub with versioning
      # Examples:
      # - standard Dockerfile: thehubusername/repositoryfoobar:v1.0.1.beta.3
      # - with name (i.e. Dockerfile.foobar): thehubusername/repositoryfoobar-helloworld:v1.0.1.beta.3
      # - Repowered example: repowered/platform-django:v1.0.1.beta.3
      - name: Set docker image tag for '${{ inputs.dockerfile_name }}'
        id: docker-image-tag-env
        env:
          hub_repo: ${{ inputs.docker_hub_username }}/${{ github.event.repository.name }}
        run: |
          DOCKERFILE=${{ inputs.dockerfile_name }}
          DOCKERFILE_NAME=$(echo $DOCKERFILE | sed 's/Dockerfile./-/;s/Dockerfile//')
          if [ ${{ contains(github.ref,'main') }} == true ]; then
            echo "image_tag=${{ env.hub_repo }}${DOCKERFILE_NAME}:${{ inputs.tag }} , ${{ env.hub_repo }}${DOCKERFILE_NAME}:latest" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ env.hub_repo }}${DOCKERFILE_NAME}:${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi
          echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: generate-image-tag-set-environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #  Log in to the desired docker hub space
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_hub_username }}
          password: ${{ secrets.docker_hub_access_token }}

      # Build the Dockerfile(s) with the image tag in the correct format and push to the hub
      - name: Build '${{ inputs.dockerfile_name }}' and push with tag '${{ inputs.tag }}'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:./"
          file: ${{ inputs.dockerfile_name }}
          push: true
          tags: ${{ needs.generate-image-tag-set-environment.outputs.image_tag }}
          build-args: |
            ARG_1=${{ inputs.build_argument_one }}
            ARG_2=${{ inputs.build_argument_two }}
            ARG_3=${{ inputs.build_argument_three }}
          secrets: |
              first=${{ secrets.docker_secret_1 }}
              second=${{ secrets.docker_secret_2 }}
              third=${{ secrets.docker_secret_3 }}
              fourth=${{ secrets.docker_secret_4 }}
              fifth=${{ secrets.docker_secret_5 }}
              sixth=${{ secrets.docker_secret_6 }}
