name: Generate and Publish GitHub Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "The Semantic Versioning GitHub tag used for version control"
        value: ${{ jobs.generate-tag.outputs.tag }}

jobs:
  generate-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.github-tag.outputs.tag }}
    if: ${{ github.event_name == 'push' 
      || (contains(github.event.workflow_run.conclusion, 'success') && (contains(github.event.workflow_run.head_branch, 'dev') 
      || contains(github.event.workflow_run.head_commit.message, '[deploy]'))) 
      || github.event.label.name == 'deploy' }}
    steps:
      # Checkout the repository with all commit history
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ github.event.workflow_run.head_sha }}

      # Automatically bump and tag with the latest SemVer formatted version.
      - name: Generate and push GitHub tag
        id: github-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
          PRERELEASE: ${{ (!contains(github.event.workflow_run.head_branch, 'dev')
            || !contains(github.event.workflow_run.head_branch, 'main'))
            || contains(github.event.workflow_run.head_commit.message, '[deploy]')
            || github.event.label.name == 'deploy' }}