name: Pytest with Coverage, Report and Job summary

on:
  workflow_call:
    inputs:
      # Required
      postgres_db:
        type: string
        required: true
      postgres_user:
        type: string
        required: true
      postgres_host:
        type: string
        required: true
      file_paths_to_cache:
        type: string
        required: true
      # Provided by caller workflow
      python_version:
        type: string
        required: true
      poetry_version:
        type: string
        required: true
      # Optional
      working_directory:
        type: string
        description: Whenever the app (i.e. manage.py) is not in the root; the location can be specified here
        default: .
      # @Deprecated: the package xdist is no longer used in this workflow
      num_test_processes:
        type: number
        description: The number of parallel test processes
        default: 2
      # Use below when it is possible for workflows (now only available for actions): https://github.com/orgs/community/discussions/58855
      #  deprecationMessage: the package xdist is no longer used in this workflow
    secrets:
      postgres_password:
        required: true
      private_pypi_url:
        required: true
      private_pypi_user:
        required: true
      private_pypi_password:
        required: true

jobs:
  pytest-with-coverage:
    name: Pytest With Postgres and Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8]

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: ${{ inputs.postgres_db }}
          POSTGRES_USER: ${{ inputs.postgres_user }}
          POSTGRES_PASSWORD: ${{ secrets.postgres_password }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: (Cached) Python and Poetry
        id: cache
        uses: repowerednl/.github/composite-actions/python-poetry-cache@REP-3541-Sonarcloud-coverage-rate-is-too-low-and-failing-on-every-PR
        with:
          python_version: ${{ inputs.python_version }}
          poetry_version: ${{ inputs.poetry_version }}
          working_directory: ${{ inputs.working_directory }}
          file_paths_to_cache: ${{ inputs.file_paths_to_cache }}
          private_pypi_url: ${{ secrets.private_pypi_url }}
          private_pypi_user: ${{ secrets.private_pypi_user }}
          private_pypi_password: ${{ secrets.private_pypi_password }}
          save_cache: ${{ matrix.group == 1 }}

      - name: Run tests with coverage in ${{ strategy.job-total }} parallel test procs
        working-directory: ${{ inputs.working_directory }}
        run: |
          poetry run coverage run -m pytest -v --splits ${{ strategy.job-total }} --group ${{ matrix.group }}
        env:
          pytest_github_report: true
          pytest_use_blanks: true
          CI: true
          POSTGRES_DB: ${{ inputs.postgres_db }}
          POSTGRES_USER: ${{ inputs.postgres_user }}
          POSTGRES_HOST: ${{ inputs.postgres_host }}
          POSTGRES_PASSWORD: ${{ secrets.postgres_password }}
          POSTGRES_PORT: 5432

      - name: Upload partial coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.head_ref || github.ref_name }}-group${{ matrix.group }}
          path: |
            ${{ inputs.working_directory }}/.coverage
          if-no-files-found: 'error'
          include-hidden-files: true

      - name: Save cache once
        if: steps.cache.outputs.cache-hit != 'true' && matrix.group == 1
        uses: actions/cache/save@v4
        with:
          path: ${{ inputs.file_paths_to_cache }}
          key: cache-python-${{ inputs.python_version }}-poetry-${{ inputs.poetry_version }}-${{ hashFiles('**/poetry.lock') }}

  combine-and-report:
    needs: pytest-with-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: (Cached) Python and Poetry
        uses: repowerednl/.github/composite-actions/python-poetry-cache@main
        with:
          python_version: ${{ inputs.python_version }}
          poetry_version: ${{ inputs.poetry_version }}
          working_directory: ${{ inputs.working_directory }}
          file_paths_to_cache: ${{ inputs.file_paths_to_cache }}
          private_pypi_url: ${{ secrets.private_pypi_url }}
          private_pypi_user: ${{ secrets.private_pypi_user }}
          private_pypi_password: ${{ secrets.private_pypi_password }}

      - name: Download all group artifacts from branch
        # Download coverage1, coverage2, etc. of the current branch
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.working_directory }}
          pattern: ${{ github.head_ref || github.ref_name }}-group*

      - name: Combine coverage and create report
        working-directory: ${{ inputs.working_directory }}
        run: |
          poetry run coverage combine ${{ github.head_ref || github.ref_name }}-group*/.coverage
          poetry run coverage report
          poetry run coverage xml

      - name: Coverage comment
        id: coverage-comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_PATH: ${{ inputs.working_directory }}
          MINIMUM_ORANGE: 80

      - name: Upload 'coverage.xml' report
        uses: actions/upload-artifact@v4
        with:
          path: coverage.xml
          if-no-files-found: 'error'
